### PR TITLE
Allow multiple interpolation methods for query points outside the boundaries

### PR DESCRIPTION
**Pull request by andrei-ng**
Hi @staticintlucas, 
I was porting some Matlab code to Rust in one of my projects. In that project I estimate the delay between two signals and your crate came in handy for interpolation.

When comparing the results with my new Rust code, I noticed that Matlab sets to NaN's the query points that are outside the input's x boundaries, whereas this crate uses the slope to "extrapolate".  

For this test in the `interp-rs` crate
```
        let x = vec![0.0, 1.0, 2.0, 3.0, 4.5];
        let y = vec![0.0, 2.0, 5.0, 3.0, 2.0];

        let xp = vec![2.5, -1.0, 7.5];
        let result = vec![4.0, -2.0, 0.0];
```
Matlab's `interp1` function with default arguments returns `[4, NaN, NaN]`

IMO no extrapolation based on slope should be performed for values outside boundaries. For the delay estimation problem I was working on, the existing version of the code can't be used for cross-correlation calculations.

### CODE REVIEW

**Comment by staticintlucas** [comment]
I don't necessarily agree that returning `T::zero()` is always correct here. `NaN` makes it clear there is an error, while zero could also be a valid result from interpolation.

It looks like various interpolation libraries have different behaviours. For example NumPy will just use the first and last values of `y`:

```python
import numpy as np

x = np.array([0.0, 1.0, 2.0, 3.0, 4.5])
y = np.array([0.0, 2.0, 5.0, 3.0, 2.0])
xp = np.array([2.5, -1.0, 7.5])

print(np.interp(xp, x, y)) # [4. 0. 2.]
```

In my own use case, extrapolation is actually the desired behaviour. I think a better solution is to introduce an `InterpMode<T>` enum to allow the user to select what behaviour they want. 

So for example `InterpMode::Extrapolate` would match the current behaviour, `InterpMode::FirstLast` would use the first and last values like NumPy, and `InterpMode::Constant(T)` could be used to set a default value. Then `InterpMode::Constant(0.0)` would match your behavour and `InterpMode::Constant(f64::NAN)` would match Matlab.

**Comment by andrei-ng** [comment]
I agree with all your points. 

How do you want to proceed? Do you want / have time to do the changes? 

Should I try do do it ?

**Comment by staticintlucas** [comment]
If you are happy to try to implement those changes, go ahead. Otherwise it might take me a week or two before I have time to look into it.

**Comment by andrei-ng** [comment]
> If you are happy to try to implement those changes, go ahead. Otherwise it might take me a week or two before I have time to look into it.

I will try to see if I can get it going next week. If I don't, I will let you know by end of next week so you can decide how to proceed.

**Comment by andrei-ng** [comment]
@staticintlucas I made a first implementation as per our disucssion. Let me know what you think.

Feel free to make changes as you think appropriate.

**Comment by andrei-ng** [comment]
Just noticed the failure. The `derive(Default)` is not needed. Can be removed.

**Comment by staticintlucas** [comment]
Cool, yeah you can either remove it or do a manual `impl<T> Default for InterpMode<T>`

The other failure is due to `num-traits` bumping its MSRV, nothing to do with your commit. I have just added a fix so if you rebase that should fix that too.

**Comment by andrei-ng** [comment]
> Cool, yeah you can either remove it or do a manual `impl<T> Default for InterpMode<T>`
> 
> The other failure is due to `num-traits` bumping its MSRV, nothing to do with your commit. I have just added a fix so if you rebase that should fix that too.

Rebased and `derive` removed (we can add it later if we really need it; I chose to remove it for now as it is not used)

**Comment by staticintlucas** [comment]
Thanks for the PR! I'll release it as `2.0` this coming weekend, I will just add a few documentation tweaks first. In the mean time you should be able to use it directly from git

**Pull request merged**
